name: Deploy Dev Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'env/dev/**'
      - 'modules/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{secrets.ARM_CLIENT_ID}}"
  ARM_CLIENT_SECRET: "${{secrets.ARM_CLIENT_SECRET}}"
  ARM_SUBSCRIPTION_ID: "${{secrets.ARM_SUBSCRIPTION_ID}}"
  ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
  TF_VAR_MONGO_URL: "${{secrets.TF_VAR_MONGO_URL}}" 
  TF_VAR_MONGO_DB: "${{secrets.TF_VAR_MONGO_DB}}" 
  TF_VAR_MAIL_SECRET_KEY: "${{secrets.TF_VAR_MAIL_SECRET_KEY}}" 
  TF_VAR_MAIL_SERVICE: "${{secrets.TF_VAR_MAIL_SERVICE}}"
  TF_VAR_MAIL_USER: "${{secrets.TF_VAR_MAIL_USER}}" 
  TF_VAR_MAPBOX_ACCESS_TOKEN: "${{secrets.TF_VAR_MAPBOX_ACCESS_TOKEN}}" 
  TF_VAR_MONGO_INITDB_ROOT_USERNAME: "${{secrets.TF_VAR_MONGO_INITDB_ROOT_USERNAME}}"  
  TF_VAR_MONGO_INITDB_ROOT_PASSWORD: "${{secrets.TF_VAR_MONGO_INITDB_ROOT_PASSWORD}}"  
  TF_VAR_DOMAIN: "${{secrets.TF_VAR_DOMAIN}}"
  ENVIRONMENT: "${{secrets.ENVIRONMENT}}"
  IP_NAME: "${{secrets.IP_NAME}}"
  LOCATION: "${{secrets.LOCATION}}"
  MAIL_SERVICE: "${{secrets.MAIL_SERVICE}}"
  MONGO_URL_DOCKER: "${{secrets.MONGO_URL_DOCKER}}"
  NIC_NAME: "${{secrets.NIC_NAME}}"
  PORT: "${{secrets.PORT}}"
  RESOURCE_GROUP: "${{secrets.RESOURCE_GROUP}}"
  SECURITY_GROUP_NAME: "${{secrets.SECURITY_GROUP_NAME}}"
  SERVER_NAME: "${{secrets.SERVER_NAME}}"
  SSH_KEY_PATH: "${{secrets.SSH_KEY_PATH}}"
  SUBNET_NAME: "${{secrets.SUBNET_NAME}}"
  VNET_NAME: "${{secrets.VNET_NAME}}"

jobs:
  terraform-plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Create SSH Keys from secrets
        run: |
          mkdir -p ./env/dev/keys
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./env/dev/keys/monomap
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./env/dev/keys/monomap.pub
          chmod 777 ./env/dev/keys/monomap
          chmod 777 ./env/dev/keys/monomap.pub
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2
          terraform_wrapper: false
            
      - name: Terraform init
        run: terraform -chdir=env/dev init
 
      - name: Terraform format
        run: terraform -chdir=env/dev fmt

      - name: Terraform validate
        run: terraform -chdir=env/dev validate
 
      - name: Terraform plan
        run: terraform -chdir=env/dev plan
      
      # - name: Terraform apply
      #   run: terraform -chdir=env/dev apply --auto-approve

          