name: Deploy Dev Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'env/dev/**'
      - 'modules/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: "${{secrets.ARM_CLIENT_ID}}"
  ARM_CLIENT_SECRET: "${{secrets.ARM_CLIENT_SECRET}}"
  ARM_SUBSCRIPTION_ID: "${{secrets.ARM_SUBSCRIPTION_ID}}"
  ARM_TENANT_ID: "${{secrets.ARM_TENANT_ID}}"
  TF_VAR_MONGO_URL: "${{secrets.TF_VAR_MONGO_URL}}" 
  TF_VAR_MONGO_DB: "${{secrets.TF_VAR_MONGO_DB}}" 
  TF_VAR_MAIL_SECRET_KEY: "${{secrets.TF_VAR_MAIL_SECRET_KEY}}" 
  TF_VAR_MAIL_SERVICE: "${{secrets.TF_VAR_MAIL_SERVICE}}"
  TF_VAR_MAIL_USER: "${{secrets.TF_VAR_MAIL_USER}}" 
  TF_VAR_MAPBOX_ACCESS_TOKEN: "${{secrets.TF_VAR_MAPBOX_ACCESS_TOKEN}}" 
  TF_VAR_MONGO_INITDB_ROOT_USERNAME: "${{secrets.TF_VAR_MONGO_INITDB_ROOT_USERNAME}}"  
  TF_VAR_MONGO_INITDB_ROOT_PASSWORD: "${{secrets.TF_VAR_MONGO_INITDB_ROOT_PASSWORD}}"  
  TF_VAR_DOMAIN: "${{secrets.TF_VAR_DOMAIN}}"
  TF_VAR_ENVIRONMENT: "${{secrets.TF_VAR_ENVIRONMENT}}"
  TF_VAR_IP_NAME: "${{secrets.TF_VAR_IP_NAME}}"
  TF_VAR_LOCATION: "${{secrets.TF_VAR_LOCATION}}"
  TF_VAR_MONGO_URL_DOCKER: "${{secrets.TF_VAR_MONGO_URL_DOCKER}}"
  TF_VAR_NIC_NAME: "${{secrets.TF_VAR_NIC_NAME}}"
  TF_VAR_PORT: "${{secrets.TF_VAR_PORT}}"
  TF_VAR_RESOURCE_GROUP: "${{secrets.TF_VAR_RESOURCE_GROUP}}"
  TF_VAR_SECURITY_GROUP_NAME: "${{secrets.TF_VAR_SECURITY_GROUP_NAME}}"
  TF_VAR_SERVER_NAME: "${{secrets.TF_VAR_SERVER_NAME}}"
  TF_VAR_SSH_KEY_PATH: "${{secrets.TF_VAR_SSH_KEY_PATH}}"
  TF_VAR_SSH_PRIVATE_KEY: "${{secrets.TF_VAR_SSH_PRIVATE_KEY}}"
  TF_VAR_SSH_PUBLIC_KEY: "${{secrets.TF_VAR_SSH_PUBLIC_KEY}}"
  TF_VAR_SUBNET_NAME: "${{secrets.TF_VAR_SUBNET_NAME}}"
  TF_VAR_VNET_NAME: "${{secrets.TF_VAR_VNET_NAME}}"
  TF_VAR_ADMIN_USERNAME: "${{secrets.TF_VAR_ADMIN_USERNAME}}"

jobs:
  terraform-plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Create SSH Keys from secrets
        run: |
          mkdir -p ./env/dev/keys
          echo "${{ secrets.TF_VAR_SSH_PRIVATE_KEY }}" > ./env/dev/keys/monomap
          echo "${{ secrets.TF_VAR_SSH_PUBLIC_KEY }}" > ./env/dev/keys/monomap.pub
          chmod 777 ./env/dev/keys/monomap
          chmod 777 ./env/dev/keys/monomap.pub
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2
          terraform_wrapper: false
            
      - name: Terraform init
        run: terraform -chdir=env/dev init
 
      - name: Terraform format
        run: terraform -chdir=env/dev fmt

      - name: Terraform validate
        run: terraform -chdir=env/dev validate
 
      - name: Terraform plan
        run: terraform -chdir=env/dev plan
      
      - name: Terraform apply
        run: terraform -chdir=env/dev apply --auto-approve

          